// Barrel export — consumers: import { Skill, Score, AgentEvent } from '@/lib/domain'
export type { EvidenceStatus, EvidenceKind, EvidenceRef, Skill } from './evidence'
export type { RoleRequirement, RankedGap } from './role'
export type { ScoreId, ScoreTraceInput, ScoreTraceContribution, ScoreTrace, Score } from './scores'
export type { InputKind, RawInput, ConsentRecord, ParsedSkillClaim, ParsedProfile } from './profile'
export type { ProofType, ActionItem, ActionPlan } from './plan'
export type { GapEntry, Intervention, CohortInsight } from './cohort'
export type { GuardrailFlag } from './guardrail'
export type { AnalysisResult } from './analysis'
export type { AgentId, PartialPayload, AgentEvent } from './events'
export { AGENT_PIPELINE } from './agents'
